//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blankspaces.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.MUNICIPIOs = new HashSet<MUNICIPIO>();
            this.USUARIOs = new HashSet<USUARIO>();
        }
        [Remote("IsUserNameAvailable", "PERSONAs", ErrorMessage = "Ya existe el nombre de usuario.")]
        [Required(ErrorMessage = "Campo obligario")]
        [Display(Name = "DUI:")]
        [StringLength(9, MinimumLength = 9, ErrorMessage = "Digite un DUI valido")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Digite un DUI Valido")]
        public string IDPERSONA { get; set; }
        public Nullable<int> IDDETALLE { get; set; }

        [Required(ErrorMessage = "Campo obligario")]
        [Display(Name = "Nombres:")]
        public string NOMBRE { get; set; }

        [Required(ErrorMessage = "Campo obligario")]
        [Display(Name = "Apellidos:")]
        public string APELLIDO { get; set; }


        [Display(Name = "Fecha de nacimiento:")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        [Required(ErrorMessage = "Campo obligario")]
        [Display(Name = "Género:")]
        public string GENERO { get; set; }
        [Display(Name = "Dirección:")]
        [Required(ErrorMessage = "Campo obligario")]
        public string DIRECCION { get; set; }


        [Required(ErrorMessage = "Campo obligario")]
        [Display(Name = "Número de teléfono:")]
        [DataType(DataType.PhoneNumber)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{2})$", ErrorMessage = "Número de telefono inválido, por favor ingrese de nuevo el número telefónico.")]
        public string TELEFONO { get; set; }

        public virtual DETALLEDEPERSONA DETALLEDEPERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUNICIPIO> MUNICIPIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
    }
}
